[package]
name = "flite-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flite-sys = { path = "flite-sys", version = "0.1.0" }

[profile.dev.package."*"]
opt-level = 3